language: scala

jdk:
  - openjdk8

before_install: sudo echo "MAVEN_OPTS='-Dorg.slf4j.simpleLogger.defaultLogLevel=error'" > ~/.mavenrc

script: mvn package

env:
  global:
    - MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.defaultLogLevel=error"

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2
