language: scala

jdk:
  - openjdk8

script: |
  mvn -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -DskipTests=true package
  mvn -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN scoverage:report

after_success: |
  bash <(curl -s https://codecov.io/bash)

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2
